# Commands to start on workspace startup
tasks :
  - init : npm install 
  command: npm start

# Ports to expose on workspace startup 
ports :
  - port: 3000
   onOpen: open-preview 

  github:
      prebuilds:
        master: true
        branches: true
        pullRequest: true
        pullRequestFromForks: true
        addCheck: true
        addComment: false
        addBadge: true